import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '800'],
  variable: '--font-raleway',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} bg-cyan-100/50`}>{children}</body>
    </html>
  )
}
