name: Main Pipeline
on:
  pull_request:
    branches: [main]
env:
  VITE_WEATHERAPP_APIKEY: ${{secrets.VITE_WEATHERAPP_APIKEY}}
jobs:
  test:
    name: Testing Pullrequest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Linting
        run: |
          npm run lint
      - name: Unit testing
        run: |
          npm run test
